services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - bigdata_network

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - bigdata_network

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - "CORE_CONF_fs_defaultFS=hdfs://namenode:8020"
    networks:
      - bigdata_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - "CORE_CONF_fs_defaultFS=hdfs://namenode:8020"
    networks:
      - bigdata_network

  jupyter_app:
    build:
      context: E:/DoAnBigData
      dockerfile: Dockerfile
    image: ecom-jupyter:latest
    container_name: jupyter_app
    depends_on:
      - spark-master
      - namenode
    ports:
      - "8888:8888" # Jupyter
      - "8501:8501" # Streamlit
    volumes:
      - "E:/DoAnBigData:/home/jovyan/work"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_TOKEN=bigdata
      - GRANT_SUDO=yes
      # (tuỳ chọn) Streamlit bật ở 0.0.0.0
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    user: root
    networks:
      - bigdata_network

  client:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: client
    depends_on:
      - namenode
      - datanode
    networks:
      - bigdata_network
    command: tail -f /dev/null

networks:
  bigdata_network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:


